app/urls.py
from django.urls import path
from . import views


app_name = "app"
urlpatterns = [
    path("", views.index, name="index"),
    path("signin/", views.signin, name="signin"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logout_view, name="logout"),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include("app.urls")),
    path('courses/', include("courses.urls")),
    path('admin/', admin.site.urls),
]

courses/urls.py
from django.urls import path
from . import views


app_name = "courses"
urlpatterns = [
    path("", views.index, name="courses"),
    path("admin_dashboard/", views.admin_dashboard, name="admin-dashboard"),
    path("<int:course_id>/", views.detail_view, name="detail"),
    path("delete/<int:course_id>/", views.delete_course, name="delete_course"),
    path("question/<int:question_id>/", views.question_view, name="question"),
    path("<int:course_id>/vote/", views.vote, name="vote"),
]

courses/models.py
''' Define the Course models, Detail and Message '''
from django.contrib.auth.models import User
from django.db import models


class Detail(models.Model):
    ''' Define the Course Detail object '''
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    img_path = models.CharField(max_length=150)
    votes = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    active = models.BooleanField(default=False)

    class Meta:
        permissions = [
                ("get_courses", "Can get courses"),
                ("member_courses", "Can get member courses"),
                ("create_courses", "Can create courses"),
                ("update_courses", "Can update courses"),
                ("delete_courses", "Can delete courses"),
                ]

    def __str__(self):
        ''' Create a visual representation when the object is created '''
        return self.title

    def change_activity(self):
        ''' Change the active status of the course '''
        self.active = not self.active

    def up_vote(self):
        ''' Increment the votes value by one '''
        self.votes += 1

    def down_vote(self):
        ''' Decrement the votes value by one '''
        self.votes -= 1

    def set_price(self, price):
        ''' Set the course price

            Args:
                price [int, float]: The new price for the course
            Return:
                Return the message: The price should be a number.
                If a non int or float value is given
        '''
        if (isintance(price, (int, float))):
            self.price = price
        else:
            return "The price should be a number"


class Message(models.Model):
    ''' Define the Message object '''
    author = models.ForeignKey(
            User,
            on_delete=models.CASCADE,
            )
    course = models.ForeignKey(
            Detail,
            on_delete=models.CASCADE,
            )
    content = models.CharField(max_length=200)

    def __str__(self):
        ''' Create a visual representation when the object is created '''
        return self.content


class Question(models.Model):
    ''' Create the Question object '''
    course = models.ForeignKey(
            Detail,
            on_delete=models.CASCADE,
            )
    content = models.CharField(max_length=255)

    class Meta:
        permissions = [
                ("create_questions", "Can create questions"),
                ]

    def __str__(self):
        ''' Create a visual representation when the object is created '''
        return self.content


class Choice(models.Model):
    ''' Create the Choice object '''
    question = models.ForeignKey(
            Question,
            on_delete=models.CASCADE,
            )
    choice_text = models.CharField(max_length=200)
    right_answer = models.BooleanField(default=False)

    class Meta:
        permissions = [
                ("create_choices", "Can create choices"),
                ]

    def __str__(self):
        ''' Create a visual representation when the object is created '''
        return self.choice_text


class Answer(models.Model):
    ''' Create the Answer object '''
    question = models.ForeignKey(
            Question,
            on_delete=models.CASCADE,
            )
    choice = models.ForeignKey(
            Choice,
            on_delete=models.CASCADE,
            )

    def __str__(self):
        ''' Create a visual representation when the object is created '''
        return self.choice

courses/forms.py
''' Define the Course forms '''
from django.core.exceptions import ValidationError
from django import forms


class DetailForm(forms.Form):
    ''' Define the course details forms '''
    title = forms.CharField(label="Title", max_length=100)
    description = forms.CharField(label="Description", max_length=255)
    price = forms.FloatField(label="Price")
    active = forms.BooleanField(label="Activate", required=False)


class CommentForm(forms.Form):
    ''' Define the course comments forms '''
    content = forms.CharField(label="Comment", max_length=200)

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if not content:
            raise ValidationError('No entry. Please write something before submitting')
        return content

class QuestionForm(forms.Form):
    ''' Define the question forms '''
    content = forms.CharField(label="Question", max_length=200)

class ChoiceForm(forms.Form):
    ''' Define the choice forms '''
    choice_text = forms.CharField(label="Choice text", max_length=200)
    right_answer = forms.BooleanField(label="Valid answer", required=False)

courses/views.py
''' Handling the views for the courses app '''
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator
from .models import Detail, Message, Question, Choice
from .forms import DetailForm, CommentForm, QuestionForm, ChoiceForm


@login_required
def index(request):
    ''' The user dashboard page currently displaying
        all the courses created with pagination, each page
        has 5 elements.
    '''
    courses = Detail.objects.all()
    paginator = Paginator(courses, 5)
    page_num = request.GET.get("page")
    courses_list = paginator.get_page(page_num)
    context = {"courses_list": courses_list}
    return render(request, "courses/index.html", context)


@login_required
@permission_required('courses.create_courses', raise_exception=True)
def admin_dashboard(request):
    ''' The site administrator dashboard page.
        This view has a form where the admin
        can create new courses.'''
    if request.method == 'POST':
        form = DetailForm(request.POST)
        if form.is_valid():
            course = Detail(**form.cleaned_data)
            course.save()
        return redirect(request.META['HTTP_REFERER'])
    else:
        form = DetailForm()
    context = {
            "form": form,
            }
    return render(request, "courses/admin_dashboard.html", context)

@login_required
@permission_required('courses.create_courses', raise_exception=True)
def delete_course(request, course_id):
    course = get_object_or_404(Detail, pk=course_id)
    course.delete()
    return redirect("/courses/")

@login_required
def detail_view(request, course_id):
    ''' This view shows the details of a specific course.
        Users can write and view comments, and also view questions.
        The site administrator has the same features of the user
        plus the ability to create questions.'''
    course = get_object_or_404(Detail, pk=course_id)
    comments = Message.objects.filter(course=course)
    comments_paginator = Paginator(comments, 5)
    comments_page_num = request.GET.get("comments_page")
    comments_list = comments_paginator.get_page(comments_page_num)
    questions = Question.objects.filter(course=course)
    questions_paginator = Paginator(questions, 5)
    questions_page_num = request.GET.get("questions_page")
    questions_list = questions_paginator.get_page(questions_page_num)
    if request.method == 'POST':
        if 'comment_submit' in request.POST:
            commentform = CommentForm(request.POST)
            if commentform.is_valid():
                message = Message(
                        author=User.objects.get(pk=request.user.id),
                        course=course,
                        **commentform.cleaned_data,
                        )
                message.save()
        elif request.user.groups.all()[0].name == 'site-admin' and\
        'question_submit' in request.POST:
            questionform = QuestionForm(request.POST)
            if questionform.is_valid():
                new_question = Question(
                        course=course,
                        **questionform.cleaned_data,
                        )
                new_question.save()
        return redirect(request.META['HTTP_REFERER'])
    else:
        commentform = CommentForm()
        questionform = QuestionForm()
    return render(
            request,
            "courses/detail.html",
            {
                "course": course,
                "commentform": commentform,
                "questionform": questionform,
                "comments_list": comments_list,
                "questions_list": questions_list,
            })


@login_required
def question_view(request, question_id):
    ''' This view handles the questions choices creation.
    '''
    question = get_object_or_404(Question, pk=question_id)
    choices = Choice.objects.filter(question=question)
    if request.method == 'POST':
        form = ChoiceForm(request.POST)
        if form.is_valid():
            choice = Choice(
                    question=question,
                    **form.cleaned_data)
            choice.save()
        return redirect(request.META['HTTP_REFERER'])
    else:
        form = ChoiceForm()
    context = {
            "question": question,
            "choices": choices,
            "form": form,
            }
    return render(request, "courses/question.html", context)


@login_required
def vote(request, course_id):
    ''' This view handles the courses voting system.
        This feature isn't implemented for the time being.

        TODO: make a call of this view using JQuery
    '''
    return HttpResponse("You're voting on the course {}.".format(course_id))

courses/templates/courses/admin_dashboard.html
{% extends "./base.html" %}

{% block content %}
<h2>Create a new course</h2>
<form method='post'>
  {% csrf_token %}
  {{form}}
  <input type="submit" value="Create">
</form>
<h2>Courses list</h2>
<ul>
  <li><a href="{% url 'courses:courses' %}">Courses List</a></li>
</ul>
{% endblock %}

courses/templates/courses/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>SkillTree</title>
  </head>
  <body>
    <nav>
      <h1>SkillTree</h1>
      <ul>
        {% if user.is_authenticated %}
	  {% if user.groups.all.0.name == 'site-admin' %}
	      <li><a href="{% url 'courses:admin-dashboard' %}">Dashboard</a></li>
          {% else %}
	      <li><a href="{% url 'courses:courses' %}">Dashboard</a></li>
          {% endif %}
          <li><a href="{% url 'app:logout' %}">Logout</a></li>
        {% else %}
	<li><a href="{% url 'app:signin' %}">Signin</a></li>
	<li><a href="{% url 'app:signup' %}">Signup</a></li>
        {% endif %}
      </ul>
    </nav>
    {% block content %}
    {% endblock %}
  </body>
</html> 

courses/templates/courses/detail.html
{% extends "./base.html" %}

{% block content %}
{% if course.active %}
  <h1>{{ course.title }}</h1>
  <p>{{ course.description }}</p>
  <p>{{ course.price }}</p>
    <h2>Question</h2>
    <ul>
    {% for question in questions_list %}
      <li><a href="{% url "courses:question" question.id %}">Question number {{question.id}}</a></li>
    {% endfor %}
    </ul>
    <div class="pagination">
    <span class="step-links">
        {% if questions_list.has_previous %}
            <a href="?questions_page=1">&laquo; first</a>
            <a href="?questions_page={{ questions_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ questions_list.number }} of {{ questions_list.paginator.num_pages }}.
        </span>

        {% if questions_list.has_next %}
            <a href="?questions_page={{ questions_list.next_page_number }}">next</a>
            <a href="?questions_page={{ questions_list.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
  {% if user.groups.all.0.name == 'site-admin' %}
    <h2>Add a Question</h2>
    <form method="post">
      {% csrf_token %}
      {{ questionform.as_p }}
      <input type="submit" name="question_submit" value="Add">
    </form>
  {% endif %}
  <h2>Comments</h2>
  <ul>
  {% for comment in comments_list %}
    <li>{{ comment.content }}</li>
  {% endfor %}
  </ul>
  <div class="pagination">
    <span class="step-links">
        {% if comments_list.has_previous %}
            <a href="?comments_page=1">&laquo; first</a>
            <a href="?comments_page={{ comments_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ comments_list.number }} of {{ comments_list.paginator.num_pages }}.
        </span>

        {% if comments_list.has_next %}
            <a href="?comments_page={{ comments_list.next_page_number }}">next</a>
            <a href="?comments_page={{ comments_list.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
  <h2>Comment</h2>
  <form method="post">
    {% csrf_token %}
    {{ commentform.as_p }}
    <input type="submit" name="comment_submit" value="Comment">
  </form>
{% else %}
  <p>This course isn't available for now. Please come back later</p>
{% endif %}
{% endblock %}

courses/templates/courses/index.html
{% extends "./base.html" %}

{% block content %}
{% if courses_list %}
  <ul>
    {% for course in courses_list %}
      <li>
        <a href="{% url 'courses:detail' course.id %}">{{ course.title }}</a>
	{% if user.groups.all.0.name == 'site-admin' %}
	<a href="{% url 'courses:delete_course' course.id %}">Delete</a>
	{% endif %}
      </li>
    {% endfor %}
  </ul>
  <div class="pagination">
    <span class="step-links">
        {% if courses_list.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ courses_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ courses_list.number }} of {{ courses_list.paginator.num_pages }}.
        </span>

        {% if courses_list.has_next %}
            <a href="?page={{ courses_list.next_page_number }}">next</a>
            <a href="?page={{ courses_list.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>
{% else %}
  <p>No courses available.</p>
{% endif %}
{% endblock %}

courses/templates/courses/question.html
{% extends "./base.html" %}

{% block content %}
<h2>Question</h2>
<p>{{ question.content }}</p>
{% if choices %}
<ul>
{% for choice in choices %}
  <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>
{% else %}
<p>No choices created yet</p>
{% endif %}
{% if user.groups.all.0.name == 'site-admin' %}
<form method='post'>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Add">
</form>
{% endif %}
{% endblock %}